### ISSUE TITLE
FileNotFoundError while training 

### ISSUE THREAD

**Issue by sb93** [YunjiKim/Unsupervised-Keypoint-Learning-for-Guiding-Class-conditional-Video-Prediction#5]
I'm getting this error while trying to run train.py as well as make_pseudo_labels.py as the file id that is being requested when model.run() is called is not found while using the Penn Action dataset.

**Comment by join16** [comment]
Sorry for the late reply. It seems that config/penn.yaml hasn't been adjusted (paths.data_dir should points to your penn action directory). 

If you have modified your config file appropriately and still get the same error, please provide us more information about your error.

**Comment by NicolasAlexandreRiess** [comment]
Unfortunately, the link https://upenn.app.box.com/v/PennAction to download the Penn Action dataset is invalid. Could you tell me how I can still download it?
